import { DatePipe } from '@angular/common';
import { CompanyProfile } from '../../models/company-profile.model';

/** HTML-escape an arbitrary value for safe interpolation into a print template. */
export function escapeHtml(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Renders the branded company header (logo + company info) used at the top of
 * every printed report. Falls back to the bundled Easy Trucking logo when the
 * profile hasn't been loaded yet.
 */
export function renderBrandedHeader(profile: CompanyProfile | null | undefined): string {
  const fallbackLogoUrl = `${window.location.origin}/assets/images/easytruckinglogo.png`;
  const logoUrl = profile?.logoUrl || fallbackLogoUrl;
  const companyName = profile?.companyName || 'EASY TRUCKING LIMITED';
  const street = profile?.street?.trim();
  const region = profile?.region?.trim();
  const country = profile?.country?.trim();
  const postal = profile?.postalAddress?.trim();
  const addressLine = postal || country
    ? `P. O. BOX ${postal || ''}${country ? ' ' + country : ''}`.trim()
    : '';
  const tin = profile?.tin ? `TIN ${profile.tin}` : '';
  const vrn = profile?.vrn ? `VRN ${profile.vrn}` : '';
  const taxLine = tin || vrn
    ? `${tin}${tin && vrn ? ' &nbsp; • &nbsp; ' : ''}${vrn}`
    : '';

  return `
    <div class="report-header">
      <div class="header-left">
        <img src="${escapeHtml(logoUrl)}" alt="Logo" style="height: 88px; object-fit: contain;">
      </div>
      <div class="header-right">
        <h1 class="company-name">${escapeHtml(companyName)}</h1>
        ${street ? `<p class="company-line">${escapeHtml(street)}</p>` : ''}
        ${region ? `<p class="company-line">${escapeHtml(region)}</p>` : ''}
        ${addressLine ? `<p class="company-line">${escapeHtml(addressLine)}</p>` : ''}
        ${taxLine ? `<p class="company-line">${taxLine}</p>` : ''}
      </div>
    </div>
  `;
}

/** Renders a row of signature lines (default: Prepared / Reviewed / Approved By). */
export function renderSignatures(
  labels: string[] = ['Prepared By', 'Reviewed By', 'Approved By']
): string {
  const blocks = labels
    .map(
      (l) => `
      <div class="signature">
        <div class="signature-line"></div>
        <div class="signature-label">${escapeHtml(l)}</div>
      </div>`
    )
    .join('');
  return `<div class="report-footer">${blocks}</div>`;
}

/** Renders the footer note with the generation timestamp. */
export function renderReportNote(): string {
  const datePipe = new DatePipe('en-US');
  const formatted = datePipe.transform(new Date(), 'dd/MM/yyyy HH:mm') ?? '';
  return `<p class="report-note">This document was generated by the Trip Management System on ${formatted}.</p>`;
}

/** Period selection used by date-range based reports. */
export type ReportPeriod = 'monthly' | 'quarterly' | 'semiannual' | 'yearly' | 'custom';

export interface PeriodSelection {
  type: ReportPeriod;
  year: number;
  month?: number;
  quarter?: number;
  half?: number;
  customStart?: string;
  customEnd?: string;
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export function formatPeriodLabel(p: PeriodSelection): string {
  switch (p.type) {
    case 'monthly':
      return p.month ? `${MONTH_NAMES[p.month - 1]} ${p.year}` : `${p.year}`;
    case 'quarterly':
      return `Q${p.quarter ?? 1} ${p.year}`;
    case 'semiannual':
      return `${p.half === 2 ? '2nd' : '1st'} Half ${p.year}`;
    case 'yearly':
      return `Year ${p.year}`;
    case 'custom':
    default: {
      const datePipe = new DatePipe('en-US');
      const start = p.customStart ? new Date(p.customStart) : null;
      const end = p.customEnd ? new Date(p.customEnd) : null;
      if (!start || !end) return 'Custom Range';
      return `${datePipe.transform(start, 'dd MMM yyyy')} — ${datePipe.transform(end, 'dd MMM yyyy')}`;
    }
  }
}

/** Renders the standard two-column meta table (Period + Date Range). */
export function renderPeriodMeta(periodLabel: string, start: Date | null, end: Date | null): string {
  const datePipe = new DatePipe('en-US');
  const fmt = (d: Date | null) => (d ? datePipe.transform(d, 'dd/MM/yyyy') ?? '-' : '-');
  return `
    <table class="meta-table">
      <tr>
        <td class="cell" style="width: 50%;">
          <div class="cell-label">Period</div>
          <div class="cell-value bold">${escapeHtml(periodLabel)}</div>
        </td>
        <td class="cell" style="width: 50%;">
          <div class="cell-label">Date Range</div>
          <div class="cell-value bold">${fmt(start)} — ${fmt(end)}</div>
        </td>
      </tr>
    </table>
  `;
}

/** Opens a print window, writes the wrapped HTML, and triggers print. */
export function openReportPrintWindow(title: string, body: string): void {
  const html = renderPrintShell(title, body);
  const win = window.open('', '_blank', 'width=980,height=760');
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 250);
}

function renderPrintShell(title: string, body: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>${REPORT_PRINT_STYLES}</style>
</head>
<body>
  ${body}
</body>
</html>`;
}

const REPORT_PRINT_STYLES = `
  @page { size: A4; margin: 12mm; }
  body { font-family: Arial, Helvetica, sans-serif; margin: 0; color: #000; background: #fff; font-size: 13px; }
  .report-document { width: 100%; max-width: 210mm; margin: 0 auto; }

  .report-header { display: flex; align-items: center; justify-content: space-between; gap: 16px; border-bottom: 4px solid #000; padding-bottom: 12px; margin-bottom: 12px; }
  .header-left { width: 30%; }
  .header-right { width: 70%; padding-left: 12px; }
  .company-name { font-size: 20px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.025em; margin: 0; }
  .company-line { font-size: 13px; margin: 2px 0; }

  .report-title { text-align: center; font-size: 22px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.05em; margin: 16px 0 12px; }
  .report-subtitle { text-align: center; font-size: 12px; color: #666; margin: -8px 0 12px; font-style: italic; }

  table { width: 100%; border-collapse: collapse; }
  .meta-table, .items-table { border: 1px solid #000; }
  .items-table { border-top: 0; }

  .cell { border: 1px solid #000; padding: 8px; vertical-align: top; }
  .cell.head { background: #f0f0f0; font-weight: 800; text-transform: uppercase; font-size: 12px; }
  .cell.head.right { text-align: right; }
  .cell.head.center { text-align: center; }
  .cell-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #444; }
  .cell-value { font-size: 14px; margin-top: 4px; }
  .bold { font-weight: 700; }
  .right { text-align: right; }
  .center { text-align: center; }

  .items-table thead tr { page-break-inside: avoid; }
  .items-table tbody tr { page-break-inside: avoid; }

  .category-row td { background: #fff7f2; font-weight: 800; font-size: 14px; }
  .category-name { color: #000; }
  .category-total { color: #f25f2f; }

  .item-row td { font-size: 12.5px; color: #333; padding: 6px 8px; }
  .item-row .item-name { padding-left: 28px; }
  .item-row .item-amount { color: #222; }

  .grand-total-row td { background: #f25f2f; color: #fff; font-size: 16px; font-weight: 800; padding: 12px 8px; border-color: #f25f2f; }
  .total-row td { background: #f0f0f0; font-weight: 800; font-size: 14px; }

  .status-badge { display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 11px; font-weight: 700; letter-spacing: 0.02em; }
  .status-good { background: #d1fae5; color: #065f46; }
  .status-warning { background: #fef3c7; color: #92400e; }
  .status-critical { background: #fee2e2; color: #991b1b; }

  .report-footer { display: flex; justify-content: space-between; gap: 40px; margin-top: 56px; }
  .signature { flex: 1; text-align: center; }
  .signature-line { border-top: 1px solid #000; height: 1px; margin-bottom: 6px; }
  .signature-label { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }

  .report-note { font-size: 10px; color: #666; text-align: center; margin-top: 36px; font-style: italic; }

  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
`;
