import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faHome,
  faCog,
  faUser,
  faSignOut,
  faPlus,
  faEdit,
  faTrash,
  faSave,
  faTimes,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faChevronLeft,
  faChevronRight,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faTruck,
  faBox,
  faMap,
  faDollarSign,
  faCalendar,
  faClipboardList,
  faEye,
  faEyeSlash,
  faDownload,
  faUpload,
  faArrowLeft,
  faArrowRight,
  faBars,
  faBell,
  faHeart,
  faStar,
  faExclamationCircle,
  faCheckCircle,
} from '@fortawesome/free-solid-svg-icons';

/**
 * Initializes Font Awesome icon library with commonly used icons.
 * Call this function once in your main app component or app.config.ts
 */
export function initFontAwesome() {
  library.add(
    faHome,
    faCog,
    faUser,
    faSignOut,
    faPlus,
    faEdit,
    faTrash,
    faSave,
    faTimes,
    faSearch,
    faFilter,
    faSort,
    faSortUp,
    faSortDown,
    faChevronLeft,
    faChevronRight,
    faCheck,
    faExclamationTriangle,
    faInfoCircle,
    faSpinner,
    faTruck,
    faBox,
    faMap,
    faDollarSign,
    faCalendar,
    faClipboardList,
    faEye,
    faEyeSlash,
    faDownload,
    faUpload,
    faArrowLeft,
    faArrowRight,
    faBars,
    faBell,
    faHeart,
    faStar,
    faExclamationCircle,
    faCheckCircle
  );
}

/**
 * Commonly used icon names for your app.
 * Use these in your templates with fa-icon component.
 */
export const FONT_AWESOME_ICONS = {
  HOME: 'home',
  SETTINGS: 'cog',
  USER: 'user',
  SIGN_OUT: 'sign-out-alt',
  ADD: 'plus',
  EDIT: 'edit',
  DELETE: 'trash',
  SAVE: 'save',
  CLOSE: 'times',
  SEARCH: 'search',
  FILTER: 'filter',
  SORT: 'sort',
  SORT_UP: 'sort-up',
  SORT_DOWN: 'sort-down',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  CHECK: 'check',
  WARNING: 'exclamation-triangle',
  INFO: 'info-circle',
  LOADING: 'spinner',
  TRUCK: 'truck',
  BOX: 'box',
  MAP: 'map',
  MONEY: 'dollar-sign',
  CALENDAR: 'calendar',
  TASKS: 'clipboard-list',
  SHOW: 'eye',
  HIDE: 'eye-slash',
  DOWNLOAD: 'download',
  UPLOAD: 'upload',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  MENU: 'bars',
  NOTIFICATION: 'bell',
  FAVORITE: 'heart',
  RATING: 'star',
  ERROR: 'exclamation-circle',
  SUCCESS: 'check-circle',
} as const;
